### ISSUE TITLE
The 6.1.0 version of the package is not installed via npm

### ISSUE THREAD

**Issue by maxkoshel** [Hapag-Lloyd/jest-puppeteer-react#70]
```
5402 error code ENOENT
5403 error errno -2
5404 error syscall chmod
5405 error enoent ENOENT: no such file or directory, chmod 'node_modules/jest-puppeteer-react/bin\debug.js'
```

**Comment by rosczja** [comment]
Hello, I checked with npm on Windows and had no problem installing the package

**Comment by maxkoshel** [comment]
On mac it doesn't work. Look above as the path to the file tries to resolve:
```
node_modules/jest-puppeteer-react/bin\debug.js
```

Looks like window style path.

**Comment by WebKieth** [comment]
macOS catalina, nodejs 11.15.0 npm 6.7.0
Big problems on installing

npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN mobx-react-devtools@6.1.1 requires a peer of mobx-react@^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-app-rewire-aliases@0.2.0 requires a peer of react-app-rewired@^1.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-app-rewire-mobx@1.0.9 requires a peer of mobx-react@>=4.2.2 < 6 but none is installed. You must install peer dependencies yourself.
npm WARN ts-pnp@1.1.2 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer-react@6.1.1 requires a peer of jest@^25.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer-react@6.1.1 requires a peer of puppeteer@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN jest-puppeteer@4.4.0 requires a peer of puppeteer@>= 1.5.0 < 3 but none is installed. You must install peer dependencies yourself.

npm ERR! path /Users/bejoy/projects/seller24/node_modules/jest-puppeteer-react/bin\debug.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/bejoy/projects/seller24/node_modules/jest-puppeteer-react/bin\debug.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bejoy/.npm/_logs/2020-04-14T16_40_34_747Z-debug.log

**Comment by ansgarm** [comment]
I just tried to reproduce the error on OS X and can only do so with node v6.9.5 (very old npm v3 something)
However using node v10.16.0 (with npm 3.10.10) it installs without error.
Maybe the issue has to do with a certain npm version?
I couldn't find any changes containing a backslash...

**Comment by rosczja** [comment]
I just released version 7.0.0 and raised required node version to at least 10. That should hopefully also require newer npm versions.

**Comment by sqrrrl** [comment]
Still see this with Node 12 & npm 6.9.0 on OSX

**Comment by sqrrrl** [comment]
Think there's some odd permission or something in the npm package.

Running `npm pack jest-puppeteer-react` and then extracting the .tgz file yields a directory with permission issues (trying to then cd into that dir fails with permission denied.)

Can do the same thing with any other package and it works fine.

There's something wrong, but I haven't been able to pinpoint it yet.
