### ISSUE TITLE
how is render working when the reactNode argument is unused

### ISSUE THREAD

**Issue by dagda1** [Hapag-Lloyd/jest-puppeteer-react#82]
Hi,

I was having a look at the code and I like the approach.

One thing I could not quite work out is how the `render` function is working.

There is a `render` function in `src/render` that looks like this:

```js
async function render(reactNode, options) {
    const { currentTestName } = expect.getState();
```

The `reactNode` argument is unused so I don't quite understand what happens in `button.browser.js`

```js
        await render(<Button label="Button" />, {
            viewport: { width: 200, height: 100, deviceScaleFactor: 1 },
        });
```

I can see there is `render.browser.js` that is used as a webpack entry.

I can also see in `entry.browser.js`, this code

```js
    const component =
        (window.__tests[testName] || {}).reactNode || React.createElement('div', null, `no component found for test "${testName}"`);

    ReactDOM.render(component, document.getElementById('main'));
    
```

But I am missing how `reactNode` ends up on `window.__tests[testName]`.

If you have time could you please help me solve this riddle?

**Comment by ansgarm** [comment]
Hi Paul,

thank you for sharing all the steps that you followed in your search for how the render function works. This helps me a lot in trying to understand which part you overlooked.

The code you are looking for can be found in `render.browser.js`
https://github.com/Hapag-Lloyd/jest-puppeteer-react/blob/548617710a9d33ae22db8e5d65b395bed501e05b/src/webpack/render.browser.js#L11

When the code is interpreted in the browser, this render function is used instead of the one in `src/render`.

It is overwritten by using an alias in the webpack configuration. In the end this line is "to blame" 😄
https://github.com/Hapag-Lloyd/jest-puppeteer-react/blob/548617710a9d33ae22db8e5d65b395bed501e05b/src/global.js#L43

I hope I could help. If there are any questions feel free to ask!

**Comment by dagda1** [comment]
thank you so much for the prompt answer.

**Comment by ansgarm** [comment]
You're welcome!
